"""Canonical machine-readable Familia memory contract."""

from __future__ import annotations

from typing import Any, Final


MEMORY_CONTRACT: Final[dict[str, Any]] = {
    "contract_version": "2.0.0",
    "authority": {
        "canonical_export": "familia.memory_contract.MEMORY_CONTRACT",
        "final_writer": "PrincipalMemoryIngestor",
        "automatic_sources": [
            "dream",
            "conversation_consolidation",
            "legacy_history_migration",
            "memory_set",
        ],
        "automatic_scopes": ["private_profile", "private_atomic_memory"],
        "owner_assignment": "server_only",
        "model_may_select_owner": False,
        "model_may_request_topic": True,
        "server_validates_topic": True,
        "model_may_create_topic": False,
    },
    "identity": {
        "principal_id": {
            "canonical_regex": "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
            "encoding": "UTF-8",
            "normalization": "none",
            "registered_required": True,
        },
        "multi_principal": {
            "explicit_actor_required": True,
            "actor_must_be_canonical": True,
            "actor_must_be_registered": True,
            "missing_or_invalid_outcome": "denied_invalid",
        },
        "executor_destination_owner_distinct": True,
    },
    "destination_registry": {
        "version": "2.0.0",
        "arbitrary_destinations_allowed": False,
        "generic_file_fallback_allowed": False,
    },
    "pair_codec": {
        "version": "pair-key-v1",
        "implementation_status": "implemented_RP-040",
        "principal_id_domain": {
            "canonical_regex": "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
            "encoding": "UTF-8",
            "normalization": "none",
        },
        "member_cardinality": 2,
        "members_distinct": True,
        "ordering": "ascending_utf8_bytes",
        "physical_grammar": (
            "pair-v1/<decimal-utf8-byte-length>:<id>/"
            "<decimal-utf8-byte-length>:<id>"
        ),
        "length_grammar": "base10_no_leading_zero_positive_integer",
        "decode_rejection_rules": [
            "invalid_prefix",
            "invalid_or_noncanonical_length",
            "invalid_utf8_or_principal_id",
            "truncated_or_surplus_member_bytes",
            "noncanonical_member_order",
            "duplicate_members",
            "trailing_bytes",
        ],
        "injective_over_full_id_domain": True,
        "shared_by": ["value_keys", "acl_generation"],
        "collision_vector": {
            "left_members": ["a_b", "c"],
            "right_members": ["a", "b_c"],
            "left_encoding": "pair-v1/3:a_b/1:c",
            "right_encoding": "pair-v1/1:a/3:b_c",
            "must_differ": True,
        },
    },
    "failure_rules": {
        "unknown_scope": {
            "outcome": "denied_invalid",
            "destination_selected": False,
            "writes": 0,
        },
        "invalid_actor_multi_principal": {
            "cases": [
                "missing",
                "blank",
                "malformed",
                "non_canonical",
                "unknown_to_registry",
            ],
            "outcome": "denied_invalid",
            "destination_selected": False,
            "writes": 0,
            "prompt_assembly_allowed": False,
        },
        "malformed_pair": {
            "cases": [
                "missing_member",
                "one_member",
                "three_or_more_members",
                "duplicate_members",
                "invalid_member",
                "noncanonical_order",
            ],
            "outcome": "denied_invalid",
            "destination_selected": False,
            "writes": 0,
        },
        "unregistered_destination": {
            "outcome": "denied_invalid",
            "fallback": "none",
            "writes": 0,
        },
    },
    "storage": {
        "profile_key": "private:<principal>:value:user_profile",
        "atomic_fact_key": "private:<principal>:memory:<fact_id>",
        "legacy_combined_key": "private:<principal>:value:memory",
        "legacy_combined_role": "migration_and_compatibility_input_only",
        "pending_migration_key": "private:<principal>:pending_migration:<id>",
        "fact_topics": {
            "assigned_by": "server",
            "homogeneous_reader_set": True,
        },
        "private_catalog": {
            "key": "private:<principal>:value:private_index",
            "entry": {
                "name": "memory:<fact_id>",
                "tags": "server_topic_tags",
            },
            "max_entries": 256,
            "overflow": "catalog_full_without_eviction",
            "update": "atomic_with_fact",
            "delete": "atomic_with_fact",
        },
    },
    "recall": {
        "own_catalog": "trusted_private_catalog",
        "foreign_projection": "authorized_fact_names_only",
        "foreign_value_projection": False,
        "foreign_catalog_projection": False,
        "foreign_profile_projection": False,
        "max_names_per_owner": 40,
        "legacy_history_fact_id": "legacy-history",
    },
    "write_routing": {
        "physical_owner": "actor",
        "owner_assigned_by": "server",
        "default_destination": "private",
        "third_party_fact_owner": "speaker",
        "foreign_private_allowed": False,
        "direct_shared_allowed": False,
        "direct_pair_allowed": False,
        "topic": {
            "form": "server_verified_private_fact_tag",
            "creation": "admin_only",
            "existing_without_shared_relations": "tag_and_notify_private_only",
            "missing_or_unavailable": "store_private_untagged_and_notify",
        },
    },
    "updates": {
        "identity": "stable_fact_id",
        "record_revision": "ts",
        "full_memory_scan_required": False,
        "operations": ["profile", "memory", "delete"],
        "delete_scope": "private_actor_fact_only",
        "delete_missing": "success",
    },
    "consolidation": {
        "supported_sources": ["vk_private", "telegram_private"],
        "automatic_destination": "private_owner_untagged",
        "owner_resolver": {
            "input": ["session_key", "messages"],
            "result": "principal_or_none",
            "before_model": True,
        },
        "archive_sink": {
            "input": ["principal", "messages"],
            "success": "return_without_exception",
            "failure": "exception",
            "failure_keeps_source_messages": True,
        },
        "retry": "reapply_stable_fact_operations",
        "session_serialization": "single_lock",
        "standalone_without_sink": "legacy_behavior",
    },
    "outcomes": {
        "legacy_row": {
            "values": [
                "imported",
                "duplicate",
                "awaiting_owner",
                "discarded_unknown",
                "retryable_failure",
            ],
            "terminal": [
                "imported",
                "duplicate",
                "awaiting_owner",
                "discarded_unknown",
            ],
        },
        "migration_command": {
            "plan": {
                "values": ["ready"],
                "terminal": ["ready"],
            },
            "apply": {
                "values": ["complete", "partial", "failed"],
                "terminal": ["complete", "partial", "failed"],
            },
        },
        "memory_mutation": {
            "committed": {
                "committed": True,
                "updated": True,
                "retryable": False,
                "version": "new_number",
            },
            "catalog_full": {
                "committed": False,
                "updated": False,
                "retryable": False,
                "version": "current_number_or_null",
            },
            "deleted": {
                "committed": True,
                "updated": True,
                "retryable": False,
                "version": "previous_number_or_null",
            },
            "absent": {
                "committed": True,
                "updated": False,
                "retryable": False,
                "version": None,
            },
            "conflict": {
                "committed": False,
                "updated": False,
                "retryable": True,
                "version": "current_number_or_null",
            },
        },
    },
    "registry": {
        "required_non_empty": True,
        "unique_fields": ["principal.id", "memx_key"],
        "exact_identity_key": "(channel,str(sender_id))",
        "telegram_derived_alias": "numeric_user_id_before_first_pipe",
        "effective_identity_keys_unique_between_principals": True,
        "invalid_states": [
            "missing",
            "empty",
            "malformed",
            "duplicate_principal_id",
            "duplicate_memx_key",
            "exact_identity_collision",
            "derived_identity_collision",
        ],
        "publish_after_full_validation": True,
        "first_install_uses_same_validation": True,
    },
    "access": {
        "decision_function": "decide_memory_read",
        "stable_reason_required": True,
        "owner_reads_own_valid_record": True,
        "family_relation_kinds": [
            "spouse_of",
            "parent_of",
            "owner_of",
            "caregiver_of",
            "guardian_of",
        ],
        "family_relation_direct_only": True,
        "family_relation_direction_matters": False,
        "common_topic_requires_family_relation": True,
        "foreign_atomic_fact_requires": [
            "trusted_catalog_match",
            "direct_family_relation",
            "verified_common_topic",
        ],
        "legacy_untagged_memory_available_to_family": False,
        "same_topic_without_family_relation": "deny",
        "pair_scope": "deny",
        "shared_scope": "deny",
        "service_keys_owner_only": True,
        "secret_records_owner_only": True,
    },
    "unknown_content": {
        "discard_before_model": True,
        "allowed_persistence": ["reason_counters"],
        "forbidden_persistence": [
            "content",
            "excerpt",
            "plain_hash",
            "cryptographic_hash",
            "derived_copy",
            "quarantine",
            "manual_review_queue",
        ],
    },
    "flat_memory": {
        "paths": ["USER.md", "MEMORY.md", "memory/MEMORY.md"],
        "may_be_memory_source": False,
        "required_size_bytes_after_transition": 0,
    },
    "soul": {
        "path": "SOUL.md",
        "initial_template": "admin/src-tauri/resources/personality.template.txt",
        "initial_creation": "atomic_create_if_absent",
        "ordinary_writer": "Admin",
        "restore_from_snapshot_is_only_exception": True,
        "preserve_bytes_during": [
            "dream",
            "dream_restore",
            "conversation_consolidation",
            "version_update",
            "legacy_transition",
            "failed_restore",
        ],
        "missing_existing_state": "integrity_error",
        "non_regular_file": "integrity_error",
    },
    "migration": {
        "report_schema": "release/memory-migration.schema.json",
        "source_contract_versions": ["legacy-unversioned", "1.0.0", "2.0.0"],
        "target_contract_version": "2.0.0",
        "migration_kinds": {
            "legacy-unversioned": "legacy_upgrade",
            "1.0.0": "legacy_upgrade",
            "2.0.0": "current_verify",
        },
        "current_verify_imports_history": False,
        "current_verify_calls_model": False,
        "current_verify": {
            "imports_history": False,
            "calls_model": False,
            "required_checks": [
                "flat_files_empty",
                "soul_verified",
                "registry_verified",
                "memx_verified",
                "receipts_verified",
                "target_invariants_verified",
                "no_unfinished_rows",
                "unknown_content_discarded",
            ],
        },
        "plan_is_applied_evidence": False,
        "exit_codes": {
            "plan": {
                "ready": 0,
            },
            "apply": {
                "complete": 0,
                "partial": 2,
                "failed": 1,
            },
        },
    },
}
